# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c62f1d98206626cce3b5e8fa8cc6b2d094c099598db600702d786d301567bdb9f317893e7c54c3155c06c2e80757dc8d475252ea8af360d27f99073a14cf2a8

test:
  secret_key_base: e98858c034ea5e2df8c18a049423404300da07bd1299f5e70b7dd329d4c7501c101aa34cf0a39caca7ee78f1cdbabd35000f0749ec418c1de7e267e5ea3628de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
